export const mockcamps = [
    {
        "created_at": "2017-04-04T05:42:33.000Z",
        "updated_at": "2018-02-10T07:40:12.000Z",
        "id": 154,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "מחנה אדמין! MIDBURN2018 3",
        "camp_name_en": "Admin`s Camp MIDBURN2018 3",
        "camp_desc_he": "מחנה אדמין! MIDBURN2018 3",
        "camp_desc_en": "Admin`s Camp MIDBURN2018 3",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "night",
        "child_friendly": 0,
        "noise_level": "medium",
        "public_activity_area_sqm": 31558,
        "public_activity_area_desc": "Sit est aut laudantium magni quo ullam dolor.",
        "support_art": 0,
        "location_comments": "Non enim at.",
        "camp_location_street": "Porro consequuntur non aut voluptatum.",
        "camp_location_street_time": "Fugit incidunt ipsa sunt dolores velit.",
        "camp_location_area": "Rem aspernatur id voluptas dignissimos.",
        "addinfo_json": null,
        "main_contact": 1,
        "moop_contact": 1,
        "safety_contact": 1,
        "contact_person_name": null,
        "contact_person_email": "Eliseo_Rolfson@hotmail.com",
        "contact_person_phone": "1-263-264-6592",
        "accept_families": 1,
        "facebook_page_url": "http://chad.info",
        "contact_person_id": 1,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-06-27T13:39:59.000Z",
        "updated_at": "2017-07-25T03:58:08.000Z",
        "id": 30,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Ducimus deleniti quo.",
        "camp_name_en": "Aut temporibus explicabo temporibus rerum nihil s",
        "camp_desc_he": "Mollitia amet expedita aut non ut molestias et.",
        "camp_desc_en": "Possimus recusandae perspiciatis in.",
        "type": "food",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "evening",
        "child_friendly": 1,
        "noise_level": "medium",
        "public_activity_area_sqm": 32500,
        "public_activity_area_desc": "Distinctio incidunt maxime vero.",
        "support_art": 1,
        "location_comments": "Eius saepe ut vitae cupiditate minima.",
        "camp_location_street": "Dolore fuga velit sunt voluptas cumque omnis sequi molestias.",
        "camp_location_street_time": "Ad earum voluptas et doloribus.",
        "camp_location_area": "Ab sunt accusamus.",
        "addinfo_json": null,
        "main_contact": 393,
        "moop_contact": 393,
        "safety_contact": 393,
        "contact_person_name": null,
        "contact_person_email": "Jadyn.Upton3@gmail.com",
        "contact_person_phone": "1-578-031-6259",
        "accept_families": 1,
        "facebook_page_url": "https://edwina.net",
        "contact_person_id": 393,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-04T05:42:33.000Z",
        "updated_at": "2018-02-10T07:40:12.000Z",
        "id": 155,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "מחנה מנהל b MIDBURN2018 4",
        "camp_name_en": "Camp Managers`s Camp MIDBURN2018 4",
        "camp_desc_he": "מחנה מנהל b MIDBURN2018 4",
        "camp_desc_en": "Camp Managers`s Camp MIDBURN2018 4",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "night",
        "child_friendly": 0,
        "noise_level": "medium",
        "public_activity_area_sqm": 31558,
        "public_activity_area_desc": "Sit est aut laudantium magni quo ullam dolor.",
        "support_art": 0,
        "location_comments": "Non enim at.",
        "camp_location_street": "Porro consequuntur non aut voluptatum.",
        "camp_location_street_time": "Fugit incidunt ipsa sunt dolores velit.",
        "camp_location_area": "Rem aspernatur id voluptas dignissimos.",
        "addinfo_json": null,
        "main_contact": 2,
        "moop_contact": 2,
        "safety_contact": 2,
        "contact_person_name": null,
        "contact_person_email": "Eliseo_Rolfson@hotmail.com",
        "contact_person_phone": "1-263-264-6592",
        "accept_families": 1,
        "facebook_page_url": "http://chad.info",
        "contact_person_id": 2,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-11-03T02:25:55.000Z",
        "updated_at": "2017-12-25T14:18:16.000Z",
        "id": 91,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Doloremque qui vitae eos illum ipsam qui doloremq",
        "camp_name_en": "Distinctio earum incidunt et eos ex et repellendu",
        "camp_desc_he": "Culpa explicabo laborum quae suscipit adipisci ex",
        "camp_desc_en": "Temporibus eum mollitia nihil deleniti nostrum co",
        "type": "workshops",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "morning",
        "child_friendly": 0,
        "noise_level": "noisy",
        "public_activity_area_sqm": 86340,
        "public_activity_area_desc": "Animi et praesentium animi facere pariatur recusandae eos.",
        "support_art": 0,
        "location_comments": "Quod et officiis inventore illum veniam nemo eum.",
        "camp_location_street": "Quasi accusamus magnam.",
        "camp_location_street_time": "Aperiam nihil architecto aut nihil suscipit est omnis.",
        "camp_location_area": "Doloribus qui quis optio voluptatem nihil incidunt suscipit eveniet.",
        "addinfo_json": null,
        "main_contact": 263,
        "moop_contact": 263,
        "safety_contact": 263,
        "contact_person_name": null,
        "contact_person_email": "Gilda.Upton80@yahoo.com",
        "contact_person_phone": "175.263.1279 x6",
        "accept_families": 0,
        "facebook_page_url": "http://amiya.name",
        "contact_person_id": 263,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-11T15:36:47.000Z",
        "updated_at": "2017-06-05T09:59:00.000Z",
        "id": 51,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Ut aut dolores aut quia qui consequuntur perspici",
        "camp_name_en": "Eligendi provident officiis sed et nesciunt nostr",
        "camp_desc_he": "Labore perferendis sed fugiat sed aperiam enim cu",
        "camp_desc_en": "Occaecati dolorum deserunt voluptas doloremque er",
        "type": "art-supporting",
        "status": "closed",
        "web_published": 0,
        "camp_activity_time": "evening",
        "child_friendly": 1,
        "noise_level": "medium",
        "public_activity_area_sqm": 95770,
        "public_activity_area_desc": "Molestiae necessitatibus commodi earum sed et eaque beatae occaecati.",
        "support_art": 0,
        "location_comments": "Commodi quo velit ad incidunt quia.",
        "camp_location_street": "Totam non quia quia dolore temporibus enim.",
        "camp_location_street_time": "Deserunt hic explicabo excepturi.",
        "camp_location_area": "Sint officia sunt in.",
        "addinfo_json": null,
        "main_contact": 404,
        "moop_contact": 404,
        "safety_contact": 404,
        "contact_person_name": null,
        "contact_person_email": "Otho.Stiedemann@hotmail.com",
        "contact_person_phone": "1-832-583-8463 ",
        "accept_families": 1,
        "facebook_page_url": "http://blanche.biz",
        "contact_person_id": 404,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-10-06T03:30:15.000Z",
        "updated_at": "2017-11-22T14:18:50.000Z",
        "id": 125,
        "event_id": "MIDBURN2018",
        "__prototype": "prod_dep",
        "camp_name_he": "Sed in temporibus enim.",
        "camp_name_en": "Est consectetur exercitationem beatae quam invent",
        "camp_desc_he": "Minus et ut recusandae at occaecati reiciendis sa",
        "camp_desc_en": "Delectus alias perferendis consequatur sapiente.",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "evening",
        "child_friendly": 0,
        "noise_level": "medium",
        "public_activity_area_sqm": 27449,
        "public_activity_area_desc": "Qui quis et libero blanditiis id sapiente corporis.",
        "support_art": 0,
        "location_comments": "Vero modi non quae.",
        "camp_location_street": "Quia deleniti iste ut et qui tempore.",
        "camp_location_street_time": "Tenetur quidem voluptatem ea vel.",
        "camp_location_area": "Inventore aspernatur possimus dolores quasi.",
        "addinfo_json": null,
        "main_contact": 221,
        "moop_contact": 221,
        "safety_contact": 221,
        "contact_person_name": null,
        "contact_person_email": "Hilbert.Fay8@hotmail.com",
        "contact_person_phone": "(652) 370-2691",
        "accept_families": 0,
        "facebook_page_url": "https://chyna.net",
        "contact_person_id": 221,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-11-30T02:12:13.000Z",
        "updated_at": "2017-12-11T04:18:19.000Z",
        "id": 87,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Consequatur libero optio voluptatibus ad est.",
        "camp_name_en": "Harum facilis quia ratione et quibusdam.",
        "camp_desc_he": "Aut unde voluptatibus laborum voluptatem.",
        "camp_desc_en": "Corporis corporis in similique itaque ratione.",
        "type": "other",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "night",
        "child_friendly": 0,
        "noise_level": "quiet",
        "public_activity_area_sqm": 58621,
        "public_activity_area_desc": "Aut culpa maiores.",
        "support_art": 1,
        "location_comments": "Officiis tenetur aut quod hic sequi eligendi accusantium facilis itaque.",
        "camp_location_street": "Vero earum veritatis veniam aut sed velit est.",
        "camp_location_street_time": "Rerum tempora dolorem et ea quas enim quis aut repudiandae.",
        "camp_location_area": "Odit molestias aut ut voluptatem illum ut iste dolorem et.",
        "addinfo_json": null,
        "main_contact": 334,
        "moop_contact": 334,
        "safety_contact": 334,
        "contact_person_name": null,
        "contact_person_email": "Donavon.Walker10@gmail.com",
        "contact_person_phone": "922.105.3018",
        "accept_families": 1,
        "facebook_page_url": "http://reese.biz",
        "contact_person_id": 334,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-06-12T22:49:39.000Z",
        "updated_at": "2017-07-10T20:38:13.000Z",
        "id": 116,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Minus eos deserunt quod adipisci mollitia laudant",
        "camp_name_en": "Ipsum perferendis in ut eligendi recusandae aut h",
        "camp_desc_he": "Delectus corrupti consequatur possimus.",
        "camp_desc_en": "Itaque ad mollitia tempore quo dolor nisi maiores",
        "type": "food",
        "status": "closed",
        "web_published": 1,
        "camp_activity_time": "evening",
        "child_friendly": 0,
        "noise_level": "noisy",
        "public_activity_area_sqm": 59216,
        "public_activity_area_desc": "Molestiae et qui adipisci rem aperiam tempora suscipit.",
        "support_art": 1,
        "location_comments": "Omnis similique consequatur unde.",
        "camp_location_street": "Sint dolores exercitationem.",
        "camp_location_street_time": "Alias praesentium quia dolores voluptatem in harum illo eos dicta.",
        "camp_location_area": "Error maiores dolorem ut.",
        "addinfo_json": null,
        "main_contact": 60,
        "moop_contact": 60,
        "safety_contact": 60,
        "contact_person_name": null,
        "contact_person_email": "Lavina_Nolan@hotmail.com",
        "contact_person_phone": "378.375.1372",
        "accept_families": 1,
        "facebook_page_url": "https://arvilla.org",
        "contact_person_id": 60,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-08-01T01:44:33.000Z",
        "updated_at": "2017-12-05T00:09:15.000Z",
        "id": 11,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Ut et animi dignissimos eaque.",
        "camp_name_en": "Iste numquam minima.",
        "camp_desc_he": "Illum tempora aut voluptatem saepe beatae ea.",
        "camp_desc_en": "Quia consequatur necessitatibus officiis quia.",
        "type": "music",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "evening",
        "child_friendly": 1,
        "noise_level": "very noisy",
        "public_activity_area_sqm": 58503,
        "public_activity_area_desc": "Eligendi in voluptatibus.",
        "support_art": 1,
        "location_comments": "Consequatur delectus rerum fuga et voluptatibus consectetur veritatis.",
        "camp_location_street": "Amet asperiores totam et ex ut illo est.",
        "camp_location_street_time": "Commodi qui incidunt amet labore qui quia molestiae.",
        "camp_location_area": "Debitis laboriosam et autem consequuntur repellat sapiente.",
        "addinfo_json": null,
        "main_contact": 78,
        "moop_contact": 78,
        "safety_contact": 78,
        "contact_person_name": null,
        "contact_person_email": "Maryam.McGlynn@hotmail.com",
        "contact_person_phone": "634-384-3537 x1",
        "accept_families": 0,
        "facebook_page_url": "https://lafayette.com",
        "contact_person_id": 78,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-09-29T06:05:03.000Z",
        "updated_at": "2018-02-20T11:50:35.000Z",
        "id": 95,
        "event_id": "MIDBURN2018",
        "__prototype": "prod_dep",
        "camp_name_he": "Cumque explicabo rem.",
        "camp_name_en": "Libero officia ut amet soluta facilis.",
        "camp_desc_he": "Consectetur ipsam tempora minima.",
        "camp_desc_en": "Harum quam sit qui error odit alias ipsa molestia",
        "type": "other",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "morning",
        "child_friendly": 0,
        "noise_level": "very noisy",
        "public_activity_area_sqm": 66201,
        "public_activity_area_desc": "Ut doloribus corrupti voluptatem eaque blanditiis est.",
        "support_art": 0,
        "location_comments": "Hic quae vero est.",
        "camp_location_street": "Pariatur eaque corrupti rem est illo.",
        "camp_location_street_time": "Alias eum dolores natus officiis sint dolor quia ipsa.",
        "camp_location_area": "Vel facere repudiandae iure eos ut debitis illum inventore.",
        "addinfo_json": null,
        "main_contact": 247,
        "moop_contact": 247,
        "safety_contact": 247,
        "contact_person_name": null,
        "contact_person_email": "Julian_Hickle81@hotmail.com",
        "contact_person_phone": "(358) 873-3901",
        "accept_families": 1,
        "facebook_page_url": "http://verla.org",
        "contact_person_id": 247,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-23T21:00:44.000Z",
        "updated_at": "2017-05-28T15:07:46.000Z",
        "id": 72,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Rerum aperiam omnis totam alias consequatur.",
        "camp_name_en": "Maiores soluta ut debitis provident nihil.",
        "camp_desc_he": "Exercitationem itaque velit qui in eos eum.",
        "camp_desc_en": "Nesciunt pariatur voluptatem nam facere deleniti ",
        "type": "music",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "noon",
        "child_friendly": 1,
        "noise_level": "noisy",
        "public_activity_area_sqm": 97599,
        "public_activity_area_desc": "Iste sed incidunt.",
        "support_art": 0,
        "location_comments": "Inventore sunt et repellat.",
        "camp_location_street": "Eligendi voluptatem eos nemo fuga sit suscipit ut.",
        "camp_location_street_time": "Mollitia voluptas eius cupiditate sed.",
        "camp_location_area": "Maiores vel nihil asperiores repellat quibusdam voluptates et.",
        "addinfo_json": null,
        "main_contact": 128,
        "moop_contact": 128,
        "safety_contact": 128,
        "contact_person_name": null,
        "contact_person_email": "Filiberto.Zieme@yahoo.com",
        "contact_person_phone": "1-693-237-8109 ",
        "accept_families": 1,
        "facebook_page_url": "https://joanne.info",
        "contact_person_id": 128,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2018-01-22T06:47:52.000Z",
        "updated_at": "2018-01-16T04:14:51.000Z",
        "id": 140,
        "event_id": "MIDBURN2018",
        "__prototype": "prod_dep",
        "camp_name_he": "Voluptatibus consequatur ipsa.",
        "camp_name_en": "Necessitatibus eligendi quis sed esse esse deleni",
        "camp_desc_he": "Tenetur voluptatibus porro corporis architecto cu",
        "camp_desc_en": "Voluptas cumque minima id consequatur iste nulla ",
        "type": "art-supporting",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "morning",
        "child_friendly": 1,
        "noise_level": "quiet",
        "public_activity_area_sqm": 32377,
        "public_activity_area_desc": "Quisquam harum doloremque ut.",
        "support_art": 1,
        "location_comments": "Iste doloremque quas tenetur.",
        "camp_location_street": "Sed id molestiae est alias cum doloribus quisquam commodi non.",
        "camp_location_street_time": "Molestiae quaerat quasi.",
        "camp_location_area": "Tenetur earum maxime beatae rem.",
        "addinfo_json": null,
        "main_contact": 132,
        "moop_contact": 132,
        "safety_contact": 132,
        "contact_person_name": null,
        "contact_person_email": "Madaline60@gmail.com",
        "contact_person_phone": "(061) 254-9285",
        "accept_families": 1,
        "facebook_page_url": "https://victor.org",
        "contact_person_id": 132,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-04T05:42:33.000Z",
        "updated_at": "2018-02-10T07:40:12.000Z",
        "id": 156,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "מחנה של משתמש רגיל MIDBURN2018 5",
        "camp_name_en": "Normal User`s Camp MIDBURN2018 5",
        "camp_desc_he": "מחנה של משתמש רגיל MIDBURN2018 5",
        "camp_desc_en": "Normal User`s Camp MIDBURN2018 5",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "night",
        "child_friendly": 0,
        "noise_level": "medium",
        "public_activity_area_sqm": 31558,
        "public_activity_area_desc": "Sit est aut laudantium magni quo ullam dolor.",
        "support_art": 0,
        "location_comments": "Non enim at.",
        "camp_location_street": "Porro consequuntur non aut voluptatum.",
        "camp_location_street_time": "Fugit incidunt ipsa sunt dolores velit.",
        "camp_location_area": "Rem aspernatur id voluptas dignissimos.",
        "addinfo_json": null,
        "main_contact": 3,
        "moop_contact": 3,
        "safety_contact": 3,
        "contact_person_name": null,
        "contact_person_email": "Eliseo_Rolfson@hotmail.com",
        "contact_person_phone": "1-263-264-6592",
        "accept_families": 1,
        "facebook_page_url": "http://chad.info",
        "contact_person_id": 3,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-08T10:50:28.000Z",
        "updated_at": "2017-03-06T23:33:36.000Z",
        "id": 17,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Quia numquam asperiores vitae hic.",
        "camp_name_en": "Odit quidem cumque atque molestias enim a ad aut ",
        "camp_desc_he": "Voluptates necessitatibus ea veniam nisi iste.",
        "camp_desc_en": "Architecto dolores maxime.",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "morning",
        "child_friendly": 0,
        "noise_level": "medium",
        "public_activity_area_sqm": 58713,
        "public_activity_area_desc": "Ut ad et modi blanditiis libero.",
        "support_art": 1,
        "location_comments": "Est at sint vitae consequatur qui qui pariatur.",
        "camp_location_street": "Impedit sequi laborum autem exercitationem dolores assumenda qui sed a.",
        "camp_location_street_time": "Velit enim quisquam similique esse maxime quia fugit rem.",
        "camp_location_area": "Dicta quia aliquam.",
        "addinfo_json": null,
        "main_contact": 64,
        "moop_contact": 64,
        "safety_contact": 64,
        "contact_person_name": null,
        "contact_person_email": "Valentin.Schaefer@yahoo.com",
        "contact_person_phone": "1-430-485-8948 ",
        "accept_families": 0,
        "facebook_page_url": "http://titus.com",
        "contact_person_id": 64,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-08-25T20:53:54.000Z",
        "updated_at": "2017-03-19T19:34:13.000Z",
        "id": 25,
        "event_id": "MIDBURN2018",
        "__prototype": "prod_dep",
        "camp_name_he": "Nesciunt vel perspiciatis in at rerum.",
        "camp_name_en": "Omnis aperiam doloribus praesentium quidem quam u",
        "camp_desc_he": "Ex dolores architecto suscipit.",
        "camp_desc_en": "Ut nam temporibus repellendus optio dignissimos.",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "night",
        "child_friendly": 1,
        "noise_level": "medium",
        "public_activity_area_sqm": 54963,
        "public_activity_area_desc": "Nam iure incidunt non rerum ipsa molestiae autem omnis.",
        "support_art": 1,
        "location_comments": "Quisquam quis nihil aut molestiae omnis sit.",
        "camp_location_street": "Rem sunt est dolor qui est iste repellendus.",
        "camp_location_street_time": "Nam perferendis et quod et.",
        "camp_location_area": "Excepturi quo est vero quidem.",
        "addinfo_json": null,
        "main_contact": 275,
        "moop_contact": 275,
        "safety_contact": 275,
        "contact_person_name": null,
        "contact_person_email": "Vilma_Brakus@gmail.com",
        "contact_person_phone": "423.025.4822 x4",
        "accept_families": 0,
        "facebook_page_url": "https://nathanial.biz",
        "contact_person_id": 275,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-04-25T18:03:00.000Z",
        "updated_at": "2017-12-12T01:25:51.000Z",
        "id": 39,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Sit quos autem porro voluptas et enim exercitatio",
        "camp_name_en": "Omnis exercitationem consequatur minus quo.",
        "camp_desc_he": "Est animi autem aut non.",
        "camp_desc_en": "Autem itaque perspiciatis.",
        "type": "drinking/bar",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "night",
        "child_friendly": 0,
        "noise_level": "noisy",
        "public_activity_area_sqm": 98397,
        "public_activity_area_desc": "Corrupti quis rerum qui ipsa.",
        "support_art": 1,
        "location_comments": "Possimus aspernatur pariatur laborum sapiente eos laboriosam nobis aut.",
        "camp_location_street": "Aut et voluptatem ea pariatur vel iste quae.",
        "camp_location_street_time": "Sed voluptatum pariatur.",
        "camp_location_area": "Nemo assumenda asperiores.",
        "addinfo_json": null,
        "main_contact": 73,
        "moop_contact": 73,
        "safety_contact": 73,
        "contact_person_name": null,
        "contact_person_email": "Leonie.Bradtke57@yahoo.com",
        "contact_person_phone": "763.138.0904",
        "accept_families": 1,
        "facebook_page_url": "https://austen.net",
        "contact_person_id": 73,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-10-09T20:20:00.000Z",
        "updated_at": "2017-10-31T22:19:13.000Z",
        "id": 65,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Ipsa et iusto et sit voluptate.",
        "camp_name_en": "Optio placeat officiis dolore assumenda sapiente ",
        "camp_desc_he": "Nam minima neque id.",
        "camp_desc_en": "Reprehenderit delectus est harum autem.",
        "type": "drinking/bar",
        "status": "closed",
        "web_published": 0,
        "camp_activity_time": "morning",
        "child_friendly": 1,
        "noise_level": "very noisy",
        "public_activity_area_sqm": 95279,
        "public_activity_area_desc": "Nam doloribus officia.",
        "support_art": 0,
        "location_comments": "Id corrupti facilis voluptatem quasi.",
        "camp_location_street": "Voluptatibus facilis est et quaerat sunt maiores eum blanditiis.",
        "camp_location_street_time": "Eos voluptatibus qui voluptatem sint corporis ratione.",
        "camp_location_area": "Quis voluptas voluptatem aperiam quia officiis quisquam sint sit.",
        "addinfo_json": null,
        "main_contact": 74,
        "moop_contact": 74,
        "safety_contact": 74,
        "contact_person_name": null,
        "contact_person_email": "Neoma.Batz@gmail.com",
        "contact_person_phone": "870.834.0637 x4",
        "accept_families": 0,
        "facebook_page_url": "https://nichole.org",
        "contact_person_id": 74,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-12-12T04:05:41.000Z",
        "updated_at": "2018-02-16T08:47:49.000Z",
        "id": 45,
        "event_id": "MIDBURN2018",
        "__prototype": "prod_dep",
        "camp_name_he": "Ut quis iste.",
        "camp_name_en": "Pariatur commodi a iusto facere libero earum.",
        "camp_desc_he": "Officia dolor labore non delectus.",
        "camp_desc_en": "Aut possimus provident optio architecto est dolor",
        "type": "food",
        "status": "closed",
        "web_published": 1,
        "camp_activity_time": "evening",
        "child_friendly": 0,
        "noise_level": "noisy",
        "public_activity_area_sqm": 31013,
        "public_activity_area_desc": "Dolores inventore dolore accusamus.",
        "support_art": 1,
        "location_comments": "Sunt et similique.",
        "camp_location_street": "Qui sunt maiores iure debitis officia quibusdam voluptatem.",
        "camp_location_street_time": "Hic harum ex voluptatem.",
        "camp_location_area": "In consequatur est aut similique ut iure.",
        "addinfo_json": null,
        "main_contact": 394,
        "moop_contact": 394,
        "safety_contact": 394,
        "contact_person_name": null,
        "contact_person_email": "Missouri.Mann@yahoo.com",
        "contact_person_phone": "949.684.8244",
        "accept_families": 0,
        "facebook_page_url": "http://magdalena.net",
        "contact_person_id": 394,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-08-31T20:45:53.000Z",
        "updated_at": "2018-02-10T01:11:53.000Z",
        "id": 49,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Laboriosam nihil quaerat cum illum quasi saepe se",
        "camp_name_en": "Quia similique ad impedit.",
        "camp_desc_he": "Itaque ea hic quia ullam.",
        "camp_desc_en": "Fuga earum voluptatem iste.",
        "type": "art-supporting",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "night",
        "child_friendly": 1,
        "noise_level": "medium",
        "public_activity_area_sqm": 947,
        "public_activity_area_desc": "Nobis excepturi blanditiis molestiae eius consequatur reprehenderit molestias enim nesciunt.",
        "support_art": 0,
        "location_comments": "Esse iusto explicabo consectetur sunt.",
        "camp_location_street": "Inventore culpa quibusdam aut ipsa sit quod non non architecto.",
        "camp_location_street_time": "Harum voluptatem dolores illo iure eos aliquam aspernatur.",
        "camp_location_area": "Quis accusantium alias optio quo quia repellendus odio pariatur.",
        "addinfo_json": null,
        "main_contact": 404,
        "moop_contact": 404,
        "safety_contact": 404,
        "contact_person_name": null,
        "contact_person_email": "Otho.Stiedemann@hotmail.com",
        "contact_person_phone": "1-832-583-8463 ",
        "accept_families": 0,
        "facebook_page_url": "https://chandler.biz",
        "contact_person_id": 404,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-11-24T04:02:30.000Z",
        "updated_at": "2017-11-18T06:11:38.000Z",
        "id": 50,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Sit blanditiis veniam eligendi minima dolorem max",
        "camp_name_en": "Quidem in nihil sunt dolores est rerum.",
        "camp_desc_he": "Odit mollitia aut aut accusamus iste.",
        "camp_desc_en": "Quis aliquid dolores deleniti voluptas sit.",
        "type": "other",
        "status": "closed",
        "web_published": 0,
        "camp_activity_time": "night",
        "child_friendly": 1,
        "noise_level": "noisy",
        "public_activity_area_sqm": 76201,
        "public_activity_area_desc": "Deserunt dolores laudantium distinctio fugit provident incidunt est.",
        "support_art": 0,
        "location_comments": "Ipsa magnam dolores sed beatae veritatis iusto voluptates sunt.",
        "camp_location_street": "Minima est ut quaerat soluta mollitia ut aut voluptas deleniti.",
        "camp_location_street_time": "Vitae numquam libero repudiandae temporibus dolores dolore voluptatem.",
        "camp_location_area": "Nihil dolores voluptatum.",
        "addinfo_json": null,
        "main_contact": 416,
        "moop_contact": 416,
        "safety_contact": 416,
        "contact_person_name": null,
        "contact_person_email": "Coty50@hotmail.com",
        "contact_person_phone": "915-260-3057",
        "accept_families": 0,
        "facebook_page_url": "http://cathryn.info",
        "contact_person_id": 416,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-08-22T01:53:02.000Z",
        "updated_at": "2017-07-13T05:45:13.000Z",
        "id": 126,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Voluptas ullam sunt qui quia.",
        "camp_name_en": "Quidem sit quia vel ex alias.",
        "camp_desc_he": "Quia et vel aliquam iste.",
        "camp_desc_en": "Non rem placeat repellat et laboriosam rem.",
        "type": "food",
        "status": "closed",
        "web_published": 1,
        "camp_activity_time": "evening",
        "child_friendly": 0,
        "noise_level": "noisy",
        "public_activity_area_sqm": 4784,
        "public_activity_area_desc": "Tempore et perferendis sequi.",
        "support_art": 0,
        "location_comments": "Nostrum eligendi itaque.",
        "camp_location_street": "Vel fugit aliquam quis et suscipit facilis veniam nostrum.",
        "camp_location_street_time": "Delectus dolor quas totam et placeat unde.",
        "camp_location_area": "Ratione qui tempore cupiditate dolores nulla.",
        "addinfo_json": null,
        "main_contact": 228,
        "moop_contact": 228,
        "safety_contact": 228,
        "contact_person_name": null,
        "contact_person_email": "Pedro_Daniel73@hotmail.com",
        "contact_person_phone": "556-827-9579 x1",
        "accept_families": 1,
        "facebook_page_url": "http://sterling.name",
        "contact_person_id": 228,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-06-11T09:45:37.000Z",
        "updated_at": "2017-07-28T13:30:56.000Z",
        "id": 93,
        "event_id": "MIDBURN2018",
        "__prototype": "theme_camp",
        "camp_name_he": "Sint est autem in ut soluta ut illo dolores.",
        "camp_name_en": "Reiciendis et quos.",
        "camp_desc_he": "Exercitationem impedit error.",
        "camp_desc_en": "Reiciendis ea non voluptas.",
        "type": "other",
        "status": "open",
        "web_published": 0,
        "camp_activity_time": "morning",
        "child_friendly": 1,
        "noise_level": "quiet",
        "public_activity_area_sqm": 28145,
        "public_activity_area_desc": "Aut laudantium et possimus esse.",
        "support_art": 1,
        "location_comments": "Quasi in at accusantium ut molestiae dolores dolore voluptas natus.",
        "camp_location_street": "Quo odit itaque velit eos id ipsum ullam suscipit voluptatem.",
        "camp_location_street_time": "Consequuntur esse voluptatem ipsam in et minus.",
        "camp_location_area": "Sint cupiditate id voluptatum voluptate cum optio illo voluptatum.",
        "addinfo_json": null,
        "main_contact": 54,
        "moop_contact": 54,
        "safety_contact": 54,
        "contact_person_name": null,
        "contact_person_email": "Neva58@yahoo.com",
        "contact_person_phone": "174.443.2537 x2",
        "accept_families": 1,
        "facebook_page_url": "https://mason.biz",
        "contact_person_id": 54,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    },
    {
        "created_at": "2017-10-21T01:22:51.000Z",
        "updated_at": "2017-05-01T22:56:38.000Z",
        "id": 2,
        "event_id": "MIDBURN2018",
        "__prototype": "art_installation",
        "camp_name_he": "Veritatis vitae error saepe voluptate consequatur",
        "camp_name_en": "Unde et voluptas tenetur.",
        "camp_desc_he": "Illo qui doloribus error expedita consequuntur et",
        "camp_desc_en": "Et quas molestiae voluptates expedita.",
        "type": "music",
        "status": "open",
        "web_published": 1,
        "camp_activity_time": "noon",
        "child_friendly": 1,
        "noise_level": "noisy",
        "public_activity_area_sqm": 51219,
        "public_activity_area_desc": "Illo velit ab quis error dolor.",
        "support_art": 0,
        "location_comments": "Aperiam vel et est repellendus animi delectus.",
        "camp_location_street": "Impedit quia consequatur facilis vel.",
        "camp_location_street_time": "Hic voluptates voluptatum voluptas vero delectus error consequuntur.",
        "camp_location_area": "Nihil facilis eaque a est corporis.",
        "addinfo_json": null,
        "main_contact": 365,
        "moop_contact": 365,
        "safety_contact": 365,
        "contact_person_name": null,
        "contact_person_email": "Aidan.Rice@hotmail.com",
        "contact_person_phone": "(917) 547-3842 ",
        "accept_families": 0,
        "facebook_page_url": "http://jazmyn.name",
        "contact_person_id": 365,
        "pre_sale_tickets_quota": null,
        "group_sale_tickets_quota": null
    }
];